/**
 * Central site configuration for SEO.
 * The production URL comes from NEXT_PUBLIC_SITE_URL (set it in .env.local / your
 * host's env). Everything SEO-related (robots, sitemap, canonical, OpenGraph,
 * JSON-LD) reads from here so there is a single source of truth for the domain.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
).replace(/\/+$/, '');

export const SITE_NAME = 'RegulatedSelf';
export const SITE_TAGLINE = 'Your Guide to Mental Wellness';
export const SITE_DESCRIPTION =
  'Evidence-based mental health articles on anxiety, depression, stress, mindfulness, and emotional wellbeing. Written by licensed professionals.';

export const TWITTER_HANDLE = '@regulatedself';

// Optional analytics / verification — set these in env when available.
export const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA_ID || '';
export const GOOGLE_SITE_VERIFICATION =
  process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '';

/** Build an absolute URL from a site-relative path. */
export function absoluteUrl(path = '/'): string {
  return `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

/**
 * Default social preview card, generated by src/app/opengraph-image.tsx.
 *
 * Next merges metadata shallowly, so a page that declares its own `openGraph`
 * replaces the root layout's entirely — including its images. Every page that
 * sets `openGraph` must therefore set an image itself or it will ship none.
 */
export const DEFAULT_OG_IMAGE = {
  url: absoluteUrl('/opengraph-image'),
  width: 1200,
  height: 630,
};

/**
 * Social profile URLs — used for Organization `sameAs` in JSON-LD, and for the
 * footer icons.
 *
 * Deliberately empty. These previously pointed at twitter.com/mindfulpath and
 * friends, which belong to unrelated real businesses, so the site was telling
 * Google it was the same entity as someone else. `sameAs` is the strongest
 * entity signal there is; claiming a profile you do not own is worse for trust
 * than claiming none. Add real handles here once the accounts exist, and both
 * the JSON-LD and the footer pick them up automatically.
 */
export const SOCIAL_LINKS: Record<string, string> = {};
